### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by pankaj-kvhld** [srome/pykliep#4]
As I execute:     

`kliep.fit(X_train, X_test)`

AttributeError: 'dict' object has no attribute 'iteritems' come. How to resolve this.

Bothe X_train and X_test sets have shape of (5000, 256)

**Comment by rafmacalaba** [comment]
`dict.iteritems()` was removed in python3 in favor of `dict.items()`, considering this was built 2 years ago.

**Comment by srome** [comment]
Good point. It may have even originally been written on python 2. Mind submitting a pull request?

**Comment by rafmacalaba** [comment]
Yeah sure, I'll check when I have the lux of time.
